### ISSUE TITLE
Where did essfedd.org go

### ISSUE THREAD

**Issue by arkytn** [essfeed/wordpress-events-manager-ess#4]
What happened to essfeed.org? Get no response for weeks now.

**Comment by RobbyAI** [comment]
Hi, we didn't received any questions.
What would you like to know or to suggest?

**Comment by arkytn** [comment]
Turn the site back on :)

I was setting up a site to use the ESS feed and using the documentation on the essfeed.org site. Now the site is totally dead so I have no place to go to get the docs. Did you know it is offline, returning nothing 

Pinging essfeed.org returns nothing which means it's dropped off of DNS.

**Comment by RobbyAI** [comment]
Woops, the web was down, we switched it on.
