### ISSUE TITLE
When adding ESS Feed -> Fatal error: Cannot use object of type WP_Error as array 

### ISSUE THREAD

**Issue by Jay031** [essfeed/wordpress-events-manager-ess#6]
Hello,

I have a correct ESS feed on one domain. But when I try to add it on my other domain, I get the following error:

Fatal error: Cannot use object of type WP_Error as array in wp-content/plugins/events-manager-ess/inc/controllers/ESS_Import.php on line 358

I did some debugging, but I was not able to fix it, I have tried disabling all other plugins, but the error still showed up.

I have Wordpress 4.2.2, the plugin page says it's compatible up to wordpress 4.0.5, I don't know if that's the issue?
And if so, is this plugin getting the support for newer wordpress versions anytime soon?

I'm looking forward to any response! :+1:

**Comment by RobbyAI** [comment]
Hi Jay,
I'll fix this issue with the latest version of Wordpress ASAP.

What you can do at the mean time is placing in:
wp-content/plugins/events-manager-ess/inc/controllers/ESS_Import.php
at the line <b>356</b> 

<code>dd( $term_array );</code>

to dump the content of the term that seems to give an error while adding to your local DB.

**Comment by Jay031** [comment]
Hmm so I commented out the part:

<code>
//if ( intval( $term_array['term_id'] ) > 0 ){
//array_push( $caregory_ids_, intval( $term_array['term_id'] ) );
//}
</code>

And put:
dd( $term_array );

But now it says:
Fatal error: Call to undefined function dd()

**Comment by Jay031** [comment]
Does anyone has any solution for my problem?? I'm willing to try everything!

**Comment by RobbyAI** [comment]
to activate the dd() function could you comment the line <b>40</b> of the file : 
<b>wp-content/plugins/events-manager-ess/inc/EM_ESS.php</b>

```
...
require_once( EM_ESS_DIR . "/inc/models/ESS_Database.php" );
require_once( EM_ESS_DIR . "/inc/models/ESS_IO.php" );

//if ( WP_DEBUG && class_exists( 'Kint' ) == FALSE ) // LINE TO COMMENT
    require_once( EM_ESS_DIR . "/inc/libs/kint-0.9/Kint.class.php" );

final class EM_ESS
{
...
```

**Comment by Jay031** [comment]
Thanks you @superbibi 

One last question;

I am now getting: Impossible to analyse the ESS Feed
it's this one: http://www.dartfreakz.nl/?em_ess=1

Can you spot what I do wrong? because I thought it should be perfectly compatible?

Thanks in advance!

**Comment by RobbyAI** [comment]
Hi Jay, 
what do you mean by "analyzing"? 
The feed seems to fine, even if the description is a bit short.

**Comment by Jay031** [comment]
It's not my own saying, it's literally the error message I get when I try to add the ESS feed.
"Impossible to analyse the ESS Feed" 
So I'm still not able to import my feed from my other domain.

**Comment by RobbyAI** [comment]
it's weird, it works on my side.
The two websites are located on the same server and share the same DB?

**Comment by Jay031** [comment]
They are on the same server but have seperate databases, that's why I want to use a feed for importing the events
