### ISSUE TITLE
`PCDATA invalid Char value` may prevent sync between calendars

### ISSUE THREAD

**Issue by wrought** [essfeed/wordpress-events-manager-ess#7]
Seems to be related to the newest version of WordPress (4.3), see [relevant wordpress support ticket](https://wordpress.org/support/topic/broken-in-43-44?replies=3#post-7394715).

Here's the [error message](https://omnicommons.org/calendar/?em_ess=1):

```
This page contains the following errors:

error on line 1095 at column 64: PCDATA invalid Char value 3
Below is a rendering of the page up to the first error.
```

I'm not able to find issues with the generated XML document, especially at the reported line number `1095` or near there.

**Comment by wrought** [comment]
I did find a few EOT (end-of-text) characters `^C` in place of what should be url-encoded or html-entity ampersand characters `&` (the encoded character being `%26` or `&amp;`, respectively) or equivalent. For example:

```
 1227          <uri>https://omnicommons.org/calendar/?post_type=event^Cp=8524</uri>^M
```

**Comment by wrought** [comment]
The patches from [this wordpress core issue](https://core.trac.wordpress.org/ticket/17780) smell like they could be the culprits for the change in behavior as of version 4.3

**Comment by RobbyAI** [comment]
Hi Wrought,
I will dig this issue. 
URL encoding in an XML file and specially within CDATA tag is really not easy.
Simply removing the url_encode() or the htmlspecialchars() will end with other issues in other circumstances (Chinese accents, URL already encoded,...).

**Comment by wrought** [comment]
@superbibi 

Heh, not sure what you mean by "dig this issue" but I'll take it as a positive sign of acknowledgement ;)

I have some experience working with XML, encoding issues, etc. I cited the WordPress patch because it seems that this bug was invoked by a WordPress upgrade. The only changes I saw in the [changelog](http://trac.wordpress.org/query?status=closed&milestone=4.3) that seemed relevant were from [the patch submitted via the issue cited above](https://core.trac.wordpress.org/attachment/ticket/17780/miqro-17780.5.patch).

Namely, [Comment:40](https://core.trac.wordpress.org/ticket/17780#comment:40) might be giving a hint:

> Looking back at the changes to the post_title field: seems this is a long existing bug that was masked by the "unusual" behaviour of `_wp_specialchars()`. The post_title is escaped first with `sanitize_post_field()` then with `htmlspecialchars()` and finally with `esc_attr()`.
> 
> As far as I see this is the only place where `esc_attr()` and `htmlspecialchars()` are nested. Not sure if fixing this at the beginning of a cycle will be any different than fixing it now.
> **_In both cases plugins that have copied that particular code from core (and don't follow WordPress development) will break.**_ Chances are that most plugin authors will test their plugins in RC or perhaps when they receive the "What's new in 4.3" email :)

**Comment by RobbyAI** [comment]
Hi Matt,
For those who want to go fast and solve the problem immediately you can replace the line **64** of the file **../wp-contents/plugins/events-manager-ess/inc/views/ESS_Feed.php**:

``` php
$event_url = self::unhtmlentities( esc_html( urldecode( $EM_Event->guid ) ) );
```

by 

``` php
$event_url = esc_html( urldecode( $EM_Event->guid ) );
```

The reason is that the Wordpress function `esc_html()` was buggy before the 4.3 version and we had to correct it with deep char encoding correction for international support. It seems that the Wordpress team have made the necessary so the function `self::unhtmlentities()` is no more required and even now generate a double encoding.

I'll dig more into this plugin and the Wordpress 4.3 version because some other issue are still there.

Thanks matt for your comment and I would really appreciate your test and comment about this issue (and other) that you might see.

**Comment by wrought** [comment]
Thanks, I've implemented the patch on our sites and will report any other issues that may arise.

I'd wait to close this issue until this change is included along with a new release of the plugin.
