### ISSUE TITLE
Auto Sync not working

### ISSUE THREAD

**Issue by jnny** [essfeed/wordpress-events-manager-ess#8]
Since the update to the plugin, manual synchronization of feeds is working again (yay!) - but automatic synchronization is not. Not sure where to look for errors - nothing in the apache error log...
https://omnicommons.org/calendar

**Comment by cameck** [comment]
Same problem here...

**Comment by RobbyAI** [comment]
A new version have been placed in the Wordpress plugin repository.
Could you tel me if the fix work for you?

Thanks

**Comment by RobbyAI** [comment]
Hi Jnny, Cameck,
can you tell me if the new release fixed the issue you were mentioning?

**Comment by cameck** [comment]
Hey Superbibi, sorry I had switched the site over to a multisite, so I am not using the plugin anymore.

**Comment by jnny** [comment]
Sorry for the delay - Syndication is still buggy. See https://omnicommons.org/calendar which should be syncing feeds from https://sudoroom.org/calendar/ and https://bayareapublicschool.org/calendar/

**Comment by BricePissard** [comment]
@jnny Could you tell me if the last release of the Event Manager ESS plugin works for you to auto-sync the ESS feeds across two websites?
